from typing import Optional

class WalleQ:
    def __new__(
        cls, leveldb: Optional[bool], sled: Optional[bool], data_path: Optional[str]
    ) -> WalleQ: ...
    def call_api(self, action: bytes | None): ...
    async def run(self, data_path: str, log_path: str): ...
