from typing import Optional

class WalleQ:
    def __new__(cls, leveldb: Optional[bool], sled: Optional[bool]) -> WalleQ: ...
    def call_api(self, action: bytes | None): ...
    async def run(self, config: bytes | None): ...
